### ISSUE TITLE
Build an  aepp authorization on mobile - iframe approach

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#21]
**Related User Stories:**

#3 

**Related Issues/Discussions:**

#3 
https://github.com/aeternity/aepp-prototypes/projects/1#card-4010781

**Blocking Issue:**
None

**Task Definition:**

- [x] Evaluate existing solutions
- [x] Create a webapp that works without browser extensions
- [x] Create keys and derived-keys
- [x] Add an option to backup keys
- [x] Create an authorization workflow with iframes
- [x] Implement an authorization example for other aepp-developers
