### ISSUE TITLE
Build a dummy for aepp authorization on desktop  - uPort, whatsapp approach

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#22]
The logic is actually still running on the mobile phone the desktop solution is just an interface to the mobile aepp and directly connected to that.

**Related User Stories:**
#3 
**Related Issues/Discussions:**
#3 
**Blocking Issue:**
None

**Task Definition:**

- [ ] Evaluate existing solutions
- [ ] Create a click-dummy that demonstrates the process
- [ ] Summarize the learnings
