### ISSUE TITLE
Protoype an engine for the conversational interface

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#24]
We need a conversational eninge that holds the stage for aepp-aexistence

**Related User Stories:**

**Related Issues/Discussions:**
#2 

**Blocking Issue:**

**Task Definition:**

- [x] Prototype an engine
- [x] Document how this could be helpful to create an aepp
- [ ] Connect it to an existing messenger platform (e.g. Telegram)

**Comment by emil-apeunit** [comment]
Conversational-machine is running and used by the [aepp-aexistence](https://github.com/aeternity/aepp-aexistence) for now. Connection with external messengers is possible, once we have a specific use case.
