### ISSUE TITLE
Add an option for the upload of the actual file in the aexistence-aepp could be (ipfs, google drive, dropbox,...)

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#28]
We want to implement an upload of the actual file in our aexistence app

**Related User Stories:**

As a User I want to access my original file that I proofed because I might loose my local copy.
When I share a proof as a User I want the receiver to have access to a copy of the proofed file.

**Related Issues/Discussions:**

**Blocking Issue:**

**Task Definition:**

- [ ] Choose a preferred file-storage for uploads matching the user stories
- [ ] Implement the upload in the current [aepp-existence](https://github.com/aeternity/aepp-aexistence) and make a PR
- [ ] Summarize and document learnings

**Comment by emil-apeunit** [comment]
We store the files, on the server for now and will implement an ipfs upload in the future
