### ISSUE TITLE
Click-dummy that shows how to send and receive AET

### ISSUE THREAD

**Issue by emil-apeunit** [aeternity/aepp-prototypes#29]
Create a frictionless UX to transfer and receive tokens

**Related User Stories:**
#1 

**Related Issues/Discussions:**
#15 

**Blocking Issue:**

**Task Definition:**

- [ ] Review existing and edit existing User Stories, add some if needed
- [ ] Create a click-dummy implementing the User Stories
- [ ] Summarize and document learnings
